[font]
size = 9.0

[font.bold]
family = "FiraMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraMono Nerd Font"
style = "Italic"

[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[keyboard]
bindings = [ { key = "Return", mods = "Shift", chars = "\n" } ]
